// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAPI.Data;

#nullable disable

namespace TestAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240726174849_SeedValueTableWithCreatedDate")]
    partial class SeedValueTableWithCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestAPI.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 26, 10, 48, 49, 561, DateTimeKind.Local).AddTicks(5178),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem dolor, hendrerit ut justo sit amet, dictum facilisis magna. Nullam pulvinar tempus leo, sit amet dapibus nisi convallis et. Pellentesque sodales vestibulum quam quis laoreet. Aenean rhoncus est nec consectetur.",
                            ImageUrl = "https://whvn.cc/47y633",
                            Name = "Lagoon",
                            Occupancy = 8,
                            Rate = 200.0,
                            Sqft = 850,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 26, 10, 48, 49, 581, DateTimeKind.Local).AddTicks(3270),
                            Details = "Phasellus tempor sapien vitae ullamcorper gravida. Aenean eget pulvinar risus. Cras molestie ligula nibh. Sed luctus condimentum leo, nec tristique tellus vulputate id. Duis semper lorem sed lacus iaculis, ac fringilla mi vestibulum. Cras vel nunc mollis, sagittis nunc ac.",
                            ImageUrl = "https://whvn.cc/47y633",
                            Name = "Park",
                            Occupancy = 4,
                            Rate = 600.0,
                            Sqft = 1500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 26, 10, 48, 49, 581, DateTimeKind.Local).AddTicks(3290),
                            Details = "Nullam bibendum lorem sed augue accumsan tempus. Ut quis bibendum eros, at malesuada odio. Duis congue dolor tincidunt orci sodales, id sagittis ante ultrices. Vivamus dapibus magna vel mi malesuada varius. Morbi volutpat eu metus dictum pretium. Proin quis tellus.",
                            ImageUrl = "https://whvn.cc/47y633",
                            Name = "Vegas Room",
                            Occupancy = 12,
                            Rate = 2000.0,
                            Sqft = 600,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 26, 10, 48, 49, 581, DateTimeKind.Local).AddTicks(3293),
                            Details = "Morbi mattis dolor mattis, faucibus quam sit amet, vestibulum orci. Quisque congue purus non ligula condimentum, at iaculis tellus faucibus. Proin eu diam sit amet diam finibus feugiat et vitae nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed.",
                            ImageUrl = "https://whvn.cc/47y633",
                            Name = "Maui Island Resort",
                            Occupancy = 2,
                            Rate = 1000.0,
                            Sqft = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 26, 10, 48, 49, 581, DateTimeKind.Local).AddTicks(3295),
                            Details = "In quis mattis erat. Mauris pellentesque diam eu volutpat sagittis. Mauris ullamcorper, elit id consectetur euismod, lacus mauris tincidunt massa, ac rhoncus risus lorem eget lectus. Aliquam erat volutpat. Maecenas efficitur, nulla nec volutpat congue, magna justo interdum nulla, at.",
                            ImageUrl = "https://whvn.cc/47y633",
                            Name = "Detroit Condo",
                            Occupancy = 6,
                            Rate = 800.0,
                            Sqft = 800,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
